language: php
php:
  - '5.3'
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'

env:
  - TEST_ENVIRONMENT=TRAVIS

before_install:
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "5.6" ]]; then composer require --dev --no-update phpunit/phpunit 5.7.5; fi

before_script:
  - composer install
  - tests/install-wp-cli.sh

script:
  - vendor/bin/phpunit

after_success:
    - bash <(curl -s https://codecov.io/bash)